#!/usr/bin/zsh

# aliases
#
# Defines some useful aliases to have.
#
# Put your useful aliases here, arranged by category. Draw from here for
# functionality. You can use this as a start for your aliases file. Pick from
# here what you would like.
#
# Usage:
#
# % source aliases
#
# will make all the aliases and functions defined in the file 'aliases'
# available to the shell. If you want there available all the time, run the
# 'source aliases' command in your '.bash_profile'.


# Normal aliases

## ls uses colors
alias ls='ls --color=auto'

## So do the various greps
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

## tail is a bit more informative
alias tail='tail -n50'

## Easy tars
alias tarx='tar -xvf'
alias tarc='tar -cvf'
## And an easy directory zip!
alias zipd='zip -rv'

## Get the battery life remaining
alias bat='cat /sys/class/power_supply/BAT1/energy_*'

## Get temperature readouts
alias temp='ls -d /sys/class/thermal/thermal_zone* | xargs -I file cat file/temp'

## fbv should just display images, nothing else. Also setup to handle many images
alias fbv='fbv --noinfo --noclear'
alias fbvgif='fbv --noinfo --noclear --delay 1'


# Functional aliases (for when a normal one won't do!)

## cd auto calls ls
cd() {
    builtin cd "$@" && ls
}

## Alias for wifi-connectivity
wifi_connect() {
    set -x
    sudo wpa_supplicant -B -Dnl80211 -iwlp4s0 -c/etc/wpa_supplicant/wpa_supplicant.conf
    sudo dhcpcd wlp4s0
    set +x
}

## Change the brightness
brightness() {
    BL_FILE='/sys/class/backlight/intel_backlight/brightness'
    BL_MAX="$(cat '/sys/class/backlight/intel_backlight/max_brightness')"
    BL_CURR="$(cat "$BL_FILE")"
    if [[ -n "$1" ]]
    then
        set -x
        sudo zsh -c "echo $(($1 * $BL_MAX / 100)) > $BL_FILE"
        set +x
    else
        echo "$((100 * $BL_CURR / $BL_MAX))%"
    fi
}

## Suspend the laptop
mem() {
    MEM_SLEEP_TIME='0'
    [[ -n "$1" ]] && MEM_SLEEP_TIME="$1"
    set -x
    sudo zsh -c 'sleep '"$MEM_SLEEP_TIME"'; sync; echo mem > /sys/power/state'
    set +x
}


# Media

## Music download
music-dl() {
    [[ -n "$1" ]] && youtube-dl -f "best" --extract-audio --audio-format "vorbis" --restrict-filenames --output "$XDG_MUSIC_DIR/Unsorted/%(title)s.%(ext)s" $@
}

## Ungif a gif
ungif() {
    GIF_FILE="$1"
    GIF_DIR="$(echo "$GIF_FILE" | cut -d'.' -f1 -)"'.ungif'
    mkdir "$GIF_DIR"
    gm convert "$GIF_FILE" +adjoin "$GIF_DIR"'/%04d.png'
}

