#!/bin/bash
#SBATCH -D /u/as/jp/ehildenb/tsp/job.%j.%N.out
#SBATCH -D /u/as/jp/ehildenb/tsp/
#SBATCH -J {JOB_NAME}
#SBATCH --get-user-env
#SBATCH --clusters=mpp1
#SBATCH --ntasks=1
#SBATCH --export=NONE
#SBATCH --time=48:00:00

/home/ehildenb/lhs/media/tsp/tsp.py {INPUT_FILE}
